openapi: 3.0.1

info:
  title: API Remessas
  description: API para simular e criar remessas
  version: 0.0.1
  contact:
    name: "Autbank"
    url: "http://www.autbank.com.br/"
    email: "contato@autbank.com.br"

servers:
  - url: /

paths:
  /remessas/simulacao:
    get:
      summary: Simular remessas
      description: Simular remessas
      operationId: simularRemessas
      parameters:
        - in: query
          name: valor
          schema:
            type: number
            example: 10.2
      responses:
        200:
          description: Remessa simulada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulacaoRemessaResponse'

  /remessas/{idRemessa}:
    get:
      summary: Devolver uma remessa específica
      description: Devolver uma remessa específica
      operationId: getRemessa
      parameters:
        - in: path
          name: idRemessa
          required: true
          schema:
            type: integer
            example: 8
      responses:
        200:
          description: Remessa obtida com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DevolveRemessaResponse'

  /remessas:
    post:
      summary: Criar nova remessa
      description: Criar nova remessa
      operationId: criarRemessas
      parameters:
        - in: query
          name: valor
          schema:
            type: number
            example: 10.2
      responses:
        200:
          description: Remessa criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CriarRemessaResponse'



components:
  schemas:
    DevolveRemessaResponse:
      type: object
      properties:
        status:
          type: string
          example: "CRIADA"
    SimulacaoRemessaResponse:
      type: object
      properties:
        valor:
          type: number
          example: 10.2
        valorEnvio:
          type: number
          example: 10.2
        taxaCambio:
          type: number
          example: 10.2

    CriarRemessaResponse:
      type: object
      properties:
        dadosRemessa:
          $ref: '#/components/schemas/DadosRemessa'
        dadosPagamento:
          $ref: '#/components/schemas/DadosPagamento'

    DadosRemessa:
      type: object
      properties:
        idRemessa:
          type: integer
        taxaCambio:
          type: number
        valorPago:
          type: number
        valorEnvio:
          type: number

    DadosPagamento:
      type: object
      properties:
        nomeBanco:
          type: string
        nroContaBanco:
          type: string
        valor:
          type: number
